name: CI

on:
  push:
    branches: [main]
    
jobs:

  deploy_production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to production
        env:
          TARGET_BRANCH: prod
        run: |
          echo "Deploying to production branch"
          git checkout -B $TARGET_BRANCH
          git merge origin/main
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push --force --set-upstream origin $TARGET_BRANCH

  deploy_homologation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to homologation
        env:
          TARGET_BRANCH: homolog
        run: |
          echo "Deploying to homologation branch"
          git checkout -B $TARGET_BRANCH
          git merge origin/main
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push --force --set-upstream origin $TARGET_BRANCH
