name: CI

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps: 
      
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.USER  }}
          password: ${{ seccrets.PASSWORD  }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            joaohong/mariadb:latest
            joaohong/wordpress:latest
